# fly.toml app configuration file generated for tawnybot on 2023-08-15T23:52:28-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tawnybot"
primary_region = "sjc"

[processes]
  app = "run -A ./mod.ts"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[mounts]
  source="app_data"
  destination="/data"

